SELECT DISTINCT ?subject ?wd ?ps_ WHERE {
  VALUES ?subject {
    %s
  }
  ?subject ?p ?statement.
  ?statement ?ps ?ps_.
  ?wd wikibase:claim ?p;
    wikibase:statementProperty ?ps.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  FILTER NOT EXISTS {?statement pq:P582 ?end}
}
ORDER BY (?wd) (?statement) (?ps_)