SELECT ?predicate ?object (COUNT(?predicate) AS ?global_count) WHERE {
  VALUES (?predicate ?object) {
    %s
  }
  ?subject ?predicate ?object.
  MINUS { ?person schema:description ?object. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
GROUP BY ?predicate ?object
ORDER BY DESC (?global_count)