SELECT ?predicate ?object (COUNT(?predicate) AS ?local_count) WHERE {
  VALUES ?subject {
    %s
  }
  ?subject ?predicate ?object.
  MINUS { ?person schema:description ?object. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
GROUP BY ?predicate ?object
FILTER (lang(?object) = 'en')
HAVING (?local_count > 0)
ORDER BY DESC(?local_count)
